Feat/follow unfollow
Calil-Silva/projeto_11_linkr pull request #20
Opened 2021-09-21 15:04 UTC by Calil-Silva

2021-09-21 23:29 UTC, leoguzi approved these changes

2021-09-22 12:23 UTC, sidneyouteiro approved these changes

2021-09-22 12:23 UTC, sidneyouteiro commented on src/pages/UserPosts.js
> +    // setFollowing(followsId.includes(parseInt(id)) || false)
Remover comentário

2021-09-22 12:26 UTC, sidneyouteiro requested changes

2021-09-22 12:26 UTC, sidneyouteiro commented on src/pages/UserPosts.js
> +  }
Dependendo das dimensões do celular e do tamanho do nome do usuario o botão sobrepoe o nome, acredito que uma alternativa melhor seria deixar o botão embaixo do nome no mobile

2021-09-22 12:35 UTC, sidneyouteiro commented on src/pages/UserPosts.js
> +  }
![image](https://user-images.githubusercontent.com/44553251/134344481-8630225e-f99a-4a4d-bf67-722fcbf3eb5a.png)

2021-09-22 14:05 UTC, calilrenner commented on src/pages/UserPosts.js
> +  }
Opa, coloquei o botão embaixo do nome @sidneyouteiro

2021-09-22 14:47 UTC, sidneyouteiro approved these changes

2021-09-22 14:47 UTC, sidneyouteiro commented on src/pages/UserPosts.js
> +      // setFollowing(followsId.includes(parseInt(id)) || false)
Remover comentário

2021-09-22 14:47 UTC, merged