Feat/searchbar
Calil-Silva/projeto_11_linkr pull request #21
Opened 2021-09-22 17:03 UTC by leoguzi

- A search on the server is triggered everytime a new char is typed and the results are shown on the layout;
- The search is triggered only when the user typed at least 3 chars and stoped for at least 300ms;
- The profiles that are followed by the user are shown in the top of the list;
- When the user click on the result, gets redirected to the respective profile;

2021-09-22 17:27 UTC, Calil-Silva commented on src/components/Header.js
> +        {window.innerWidth > 1000 ? <SearchUser /> : ""}
Leo! Estou adotando, quando lembro, de fazer a seguinte sintax:
        {window.innerWidth > 1000 && <SearchUser />}
Assim evitamos de colocar "".

2021-09-22 17:35 UTC, Calil-Silva commented on src/components/SearchUser.js
> +          )}
Aqui também daria pra usar o && para não voltar o "".

2021-09-22 17:37 UTC, Calil-Silva commented on src/components/SearchUser.js
> +      )}
Aqui também daria pra usar o && para não voltar o "".

2021-09-22 17:47 UTC, Calil-Silva commented
In general, it looks all right. All requirements seems to be running on Vercel.

Tips: We can use "&&" to "||" instead of returning "" in JSX. Something like:

```
// {true && true}, instead of {true ? x : ""}
// {true || false}, instead of {true ? x : y} 
```

2021-09-22 17:57 UTC, Calil-Silva reviewed
In general, it looks all right. All requirements seems to be running on Vercel.

Tips: We can use "&&" or "||" instead of returning "" in JSX. Something like:

```
// {true && true}, instead of {true ? x : ""}
// {true || false}, instead of {true ? x : y}
```

2021-09-22 19:24 UTC, Calil-Silva approved these changes
In general, it looks all right. All requirements seems to be running on Vercel.

2021-09-23 04:49 UTC, sidneyouteiro requested changes

2021-09-23 04:49 UTC, sidneyouteiro commented on src/components/Header.js
> +        {window.innerWidth > 1000 ? <SearchUser /> : ""}
`{window.innerWidth > 1000 && <SearchUser />}`

2021-09-23 04:49 UTC, sidneyouteiro commented on src/components/SearchUser.js
> +          )}
```
{user.isFollowingLoggedUser && (
            <TextContainer>
              <Dot />
              <span>following</span>
            </TextContainer>
          )}
```

2021-09-23 04:49 UTC, sidneyouteiro commented on src/components/SearchUser.js
> +      )}
```
{searchField.length > 2 && <BlockContent onClick={() => setSearchField("")} />}
```

2021-09-23 04:49 UTC, sidneyouteiro commented on src/components/SearchUser.js
> +        )}
```
{searchField.length > 2 && !searchResult.length && (
          <a>
            <Result>
              <span>Nenhum resultado...</span>
            </Result>
          </a>
        )}
```

2021-09-23 04:49 UTC, sidneyouteiro commented on src/pages/Hashtag.js
> +        {window.innerWidth < 1000 ? <SearchUser /> : ""}
`{window.innerWidth < 1000 && <SearchUser />}`

2021-09-23 04:49 UTC, sidneyouteiro commented on src/pages/MyLikes.js
> +        {window.innerWidth < 1000 ? <SearchUser /> : ""}
`{window.innerWidth < 1000 && <SearchUser />}`

2021-09-23 04:49 UTC, sidneyouteiro commented on src/pages/MyPosts.js
> +        {window.innerWidth < 1000 ? <SearchUser /> : ""}
`{window.innerWidth < 1000 && <SearchUser />}`

2021-09-23 04:49 UTC, sidneyouteiro commented on src/pages/Timeline.js
> +            {window.innerWidth < 1000 ? <SearchUser /> : ""}
`{window.innerWidth < 1000 && <SearchUser />}`

2021-09-23 04:49 UTC, sidneyouteiro commented on src/pages/UserPosts.js
>      [follows] // eslint-disable-line react-hooks/exhaustive-deps
Remover comentário na linha 39, caso dê warning no useEffect me mande msg com o warning que eu já tenho uma ideia de como resolver

2021-09-23 04:49 UTC, sidneyouteiro commented on src/pages/UserPosts.js
> +        {window.innerWidth < 1000 ? <SearchUser /> : ""}
`{window.innerWidth < 1000 && <SearchUser />}`

2021-09-23 21:41 UTC, sidneyouteiro approved these changes

2021-09-23 21:41 UTC, merged