Feat/comments
Calil-Silva/projeto_11_linkr pull request #22
Opened 2021-09-22 18:33 UTC by thipereira02

2021-09-22 19:10 UTC, Calil-Silva commented on src/components/Comments.js
> +    console.log(postComments)
Thiago, could you remove this console.log?

2021-09-22 19:16 UTC, Calil-Silva commented on src/pages/acessControl/Login.js
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
Thiago, please, could you remove this comment?

2021-09-22 19:27 UTC, Calil-Silva approved these changes
In general, it looks all right. All requirements seems to be running on Vercel.

2021-09-23 05:37 UTC, sidneyouteiro requested changes
CSS isn't prepared for big comments that don't have whitespace, I think [this](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) might help
![image](https://user-images.githubusercontent.com/44553251/134458516-b3d1a198-de63-4150-90b0-0ad04bf490c8.png)

2021-09-24 13:09 UTC, sidneyouteiro approved these changes

2021-09-25 04:32 UTC, sidneyouteiro approved these changes

2021-09-25 04:32 UTC, merged