Feat/use interval
Calil-Silva/projeto_11_linkr pull request #25
Opened 2021-09-24 00:15 UTC by Calil-Silva

2021-09-24 00:40 UTC, leoguzi commented on src/pages/Timeline.js
> +    console.log(onChangePost)
console.log left behind!

2021-09-24 00:41 UTC, leoguzi requested changes

2021-09-24 00:41 UTC, leoguzi commented on src/pages/Timeline.js
> +    console.log(onChangePost)
console.log left behind!

2021-09-24 15:54 UTC, Calil-Silva commented on src/pages/Timeline.js
> +    console.log(onChangePost)
console removed

2021-09-24 16:20 UTC, leoguzi approved these changes
Nice job! Everything looks fine.

2021-09-25 05:35 UTC, sidneyouteiro commented
Just fix the merge conflicts, then i will approve 👍🏽

2021-09-25 20:34 UTC, Calil-Silva commented
Fixed conflicts.

2021-09-25 21:08 UTC, sidneyouteiro approved these changes

2021-09-25 21:08 UTC, merged