Feat/timeline
Calil-Silva/projeto_11_linkr pull request #4
Opened 2021-09-15 17:18 UTC by Calil-Silva

It refers to "Como usuário logado, quero ver os posts da minha timeline na rota "/timeline"". I alse implemented part of mobile design.

Please, see that i created the "createUser.js" that contains axios requests. Its just for testing, this component will may not be in the final version.

2021-09-15 19:31 UTC, sidneyouteiro requested changes
Qualquer dúvida só mandar msg 🤙🏽

2021-09-15 19:31 UTC, sidneyouteiro commented on src/hashtag/Hashtag.js
> +}
Isso não faz parte do escopo da tarefa

2021-09-15 19:31 UTC, sidneyouteiro commented on src/timeline/Timeline.js
> +    }
Poderiamos pegar o token via postman e deixar direto no contexto do usuário assim iria tirar a necessidade de ter essas funções.

2021-09-15 19:31 UTC, sidneyouteiro commented on src/timeline/Timeline.js
> +        login().then(res => setToken(res.data.token)).catch(err => console.log(err.response))
Poderíamos usar algumas quebras de linha para aumentar a legibilidade.

2021-09-15 19:31 UTC, sidneyouteiro commented on src/timeline/Timeline.js
> +            getPosts(token).then(res => setPosts(res.data.posts)).catch(err => SetErrPosts('Houve uma falha ao obter os posts, por favor atualize a página'))
Poderíamos usar algumas quebras de linha para aumentar a legibilidade.

2021-09-15 19:31 UTC, sidneyouteiro commented on src/timeline/Timeline.js
> +    }
Acredito que não compensa transformar esse procedimento em uma função, pois não terá reaproveitamento desse código.

2021-09-15 19:31 UTC, sidneyouteiro commented on src/timeline/Timeline.js
> +    }
E poderíamos estruturar as condicionais de tal forma que fosse simplificar o procedimento como um todo, exemplo:
```
if(errPosts === "'') {
     // codigo
} else {
        return (
             <ErrorMsg>{errPosts}</ErrorMsg>
          )
}
```
Poderíamos deixar como:
```
if(errPosts) 
     return (
             <ErrorMsg>{errPosts}</ErrorMsg>
          )
if(//demais verificações)
```
mas a estrutura que você fez em relação aos posts tá de boa, só peço que deixe a forma que os posts são carregados genéricos de tal forma que seja reaproveitado para tarefas futuras que vão exigir similaridade.

2021-09-15 19:31 UTC, sidneyouteiro commented on src/user/User.js
> +}
Isso não faz parte do escopo da tarefa.

2021-09-15 20:28 UTC, Calil-Silva commented on src/user/User.js
> +}
Ajustado (removido)

2021-09-15 20:28 UTC, Calil-Silva commented on src/hashtag/Hashtag.js
> +}
Ajustado (removido)

2021-09-15 20:29 UTC, Calil-Silva commented on src/timeline/Timeline.js
> +    }
Aguardando o Leo, ele está fazendo o context

2021-09-15 20:30 UTC, calilrenner commented on src/timeline/Timeline.js
> +        login().then(res => setToken(res.data.token)).catch(err => console.log(err.response))
Sid, coloquei assim, o que acha?

        login()
            .then(res => setToken(res.data.token))
            .catch(err => console.log(err.response))
    }, []);

2021-09-15 20:31 UTC, Calil-Silva commented on src/timeline/Timeline.js
> +            getPosts(token).then(res => setPosts(res.data.posts)).catch(err => SetErrPosts('Houve uma falha ao obter os posts, por favor atualize a página'))
Sid, coloquei assim, o que acha?

if (token !== '') {
            getPosts(token)
                .then(res => setPosts(res.data.posts))
                .catch(err => SetErrPosts('Houve uma falha ao obter os posts, por favor atualize a página'))
        } else {
            return;
        }
    }, [token]);

2021-09-15 21:09 UTC, Calil-Silva commented on src/timeline/Timeline.js
> +    }
Sid, deixei assim:

```
function loadPosts() {
        if (errPosts === '') {
            return (
                <ErrorMsg>{errPosts}</ErrorMsg>
            )
        }

        if (posts === '') {
            return (
                <Container>
                    <Loader />
                    <LoaderText>Carregando...</LoaderText>
                </Container>
            )
        } else if (posts.length === 0) {
            return (
                <ErrorMsg>Nenhum post encontrado</ErrorMsg>
            )
        } else {
            return (
                <Main>
                    <div>
                        <Header />
                        <Title>timeline</Title>
                        <PostCreation />
                        {posts.map(post => <TimelinePost key={post.id} {...post} />)}
                    </div>
                    <DivHashTag />
                </Main>
            )
        }
    }
```

2021-09-15 23:49 UTC, Calil-Silva commented on src/timeline/Timeline.js
> +    }
Sid, já ajustei conforme alterações do leo. Requisições estão no services agora,

2021-09-16 02:31 UTC, sidneyouteiro commented
Calil só vou pedir para que resolva os conflitos de merge que ocorreram nos arquivos:

- package.json

- src/App.js

- src/service/api.service.js

2021-09-16 03:16 UTC, merged